spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:community
    username : sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: community

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ktb-neo-very-long-secret-key-that-is-at-least-32-chars
  expiration: 3600000
  refresh-expiration: 604800000
